# Configuration file. Made with ❤ by frafol.
# For support: https://discord.com/invite/sTSwaGBCdC

settings:

  update_check: true
  auto_update: true
  stats: true

  # Removes some credit messages, if you want to support the developer, please leave this to false.
  credit_less: false

  # Knockbackinator's usage permission.
  # Use "" to disable this feature.
  usage_permission: "knockbinator.get"

  # Knockbackinator's reload permission.
  reload_permission: "knockbinator.reload"

  # Activate this if you want pvp to be possible only with the Knockbackinator.
  prevent_other_item_pvp: true

  # Activate it if you want the player not to take damage with the Knockbackinator.
  prevent_taking_damage: true

  # Activate it if you want the effects of the player who's taking the Knockbackinator to be removed.
  remove_all_effects: true

  # Knockbackinator's knockback settings.
  knockback:

    # Delay of any hit in milliseconds.
    hit_delay: 1

    # Here you can change the stick knockback.
    x_increment: "0"
    y_increment: "0.2"
    z_increment: "0"

  # Knockbackinator's item settings.
  item:

    # Sets the give delay (in ticks).
    # Can be useful if in your server there is a plugin that clears the inventory on join.
    # Do not set it to 0 or less.
    delay: 5

    # Sets the Knockbackinator's item slot.
    slot: 4

    # Sets the Knockbackinator's item name.
    name: "&cKnockbackinator"

    # Sets the Knockbackinator's item lore.
    lore:
      - "&7Use this item to a"
      - "&7player that you want to"
      - "&7knockback &dup&7."

    # Some other settings about the Knockbackinator's item.
    prevent_break: true
    prevent_drop: true
    prevent_move: true

# Enjoy!